### ISSUE TITLE
Add guard for is_binary

### ISSUE THREAD

**Issue by fireproofsocks** [martinsvalin/html_entities#23]
It would be nice if there were an `is_number` guard on the `HtmlEntities.encode/1` function.

Currently, when I try this:
```
iex> HtmlEntities.encode(123)
```

I would expect the output to be `"123"` (i.e. have `to_string()` applied).

Instead, the actual result is that an error is raised:

```
iex> HtmlEntities.encode(123)
** (FunctionClauseError) no function clause matching in HtmlEntities."-encode/1-lbc$^0/2-0-"/2

    The following arguments were given to HtmlEntities."-encode/1-lbc$^0/2-0-"/2:

        # 1
        123

        # 2
        ""

    lib/html_entities.ex:78: HtmlEntities."-encode/1-lbc$^0/2-0-"/2
```

I think the guard would make the function's intent a bit clearer and the error would be a bit more informative -- it would return something like 
```
Attempted function clauses (showing 1 out of 1):

        def encode(string) when is_binary(string)
```

It might be nice to handle numbers too and maybe raise a more informative error when other input types are encountered.

**Comment by martinsvalin** [comment]
Hi, thanks for the suggestion. I don't think this library should apply `to_string` to inputs, but I agree that an `is_binary` guard clause gives a better error message and probably reinforces the intent when someone reads the source. Guard clauses were added for both `encode/1` and `decode/1` in a7f2011

**Comment by fireproofsocks** [comment]
Thank you for understanding my intention!  Of course, I had meant to write "It would be nice if there were an is_binary guard", but of course, I got distracted and wrote `is_binary`.  Thanks for your quick response!
