### ISSUE TITLE
Add last-resort function to raise an error

### ISSUE THREAD

**Issue by DavsX** [martinsvalin/html_entities#4]
Would it be a good idea to add a replace_entity function at the end (matching anything) , that would raise an error with the message, like "Cannot decode &?34;"?
Right now in that case it would only say, that no matching function was found, but the character/html entity itself is not part of the error message, which can be unclear.

Ideas?

Edit: This makes more sense: https://github.com/martinsvalin/html_entities/commit/0ddcd2381219d83ba54e7ca81d1459944c774b1a

**Comment by martinsvalin** [comment]
My first approach is to ignore unrecognized entities, and I think this is a good default. I could see two ways of having a stricter version: either by providing a `decode!` that gives an error like you described or by giving `decode` a list of options, including a `:strict` flag.

**Comment by martinsvalin** [comment]
Re-opening ;)

I think having a strict version could be a good idea.

**Comment by DavsX** [comment]
In the current form "&#something;" raises error as well, because it tries to create an integer from "something". Should we make it safe? I've tried adding a 'when is_number(code)' to the function definition, but the realized, that `code` is a string.

**Comment by martinsvalin** [comment]
Good point. These tests would fail.

```elixir
assert decode("&#nosuchentity;") == "&#nosuchentity;"
assert decode("&#xxxx;") == "&#xxxx;"
```

**Comment by martinsvalin** [comment]
I've since added and fixed the tests mentioned above. See 08346d9.

**Comment by martinsvalin** [comment]
Closing this issue. I'm open to adding a `:strict` option, but I think it'd make more sense if someone actually was planning to use it. ;)
