### ISSUE TITLE
Releasing an update

### ISSUE THREAD

**Issue by DavsX** [martinsvalin/html_entities#6]
Would you consider releasing an updated version (0.2.0 or 0.1.1) with the newest code?

**Comment by martinsvalin** [comment]
I will, but I'm on the road without my computer (and hence private key), so I can't publish a hex package until Monday. Sorry for the delay.

**Comment by DavsX** [comment]
No problem.

**Comment by martinsvalin** [comment]
Done. https://hex.pm/packages/html_entities

**Comment by DavsX** [comment]
+1
