### ISSUE TITLE
Mark external file dependency 

### ISSUE THREAD

**Issue by martinsvalin** [martinsvalin/html_entities#9]
Using `@external_resource path_to_file`, mark the dependency between html_entities.ex and hyml_entities_list.txt. This way, Elixir will know to recompile the module if the txt changes.

**Comment by jwarlander** [comment]
This one seems to be sorted out already...

```bash
$ grep external_resource lib/html_entities.ex
  @external_resource "lib/html_entities_list.txt"
  codes = HtmlEntities.Util.load_entities(@external_resource)
```

...and working nicely :)

```bash
$ mix do deps.get, compile
# lots of stuff happens..
$ mix compile
$ echo "myownamp,&,38" >> lib/html_entities_list.txt
$ mix compile
Compiled lib/html_entities.ex
```

**Comment by martinsvalin** [comment]
@jwarlander thanks, totally forgot about the issue I opened to remind myself. 🙃
